-- 슬롯 패치 명세 v2.0 개정 — 어깨라인(쇄골) 슬롯 + A+ 등급
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'SHOULDER_LINE_L';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'SHOULDER_LINE_R';
ALTER TYPE "SlotGrade" ADD VALUE IF NOT EXISTS 'A_PLUS';
